### ISSUE TITLE
Missed spider in request_to_dict

### ISSUE THREAD

**Issue by edorofeev** [scrapy-plugins/scrapy-crawlera-fetch#5]
I have a error when I started to use the latest version
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.8/site-packages/scrapy/core/downloader/middleware.py", line 36, in process_request
    response = yield deferred_from_coro(method(request=request, spider=spider))
  File "/app/python/lib/python3.8/site-packages/crawlera_fetch/middleware.py", line 106, in process_request
    "original_request": request_to_dict(request),
  File "/usr/local/lib/python3.8/site-packages/scrapy/utils/reqser.py", line 19, in request_to_dict
    cb = _find_method(spider, cb)
  File "/usr/local/lib/python3.8/site-packages/scrapy/utils/reqser.py", line 92, in _find_method
    raise ValueError("Function %s is not a method of: %s" % (func, obj))
ValueError: Function <bound method UniversalParserSpider.parse_item of <AmazonExtractionSpider 'amazon_extraction' at 0x7f56023bf670>> is not a method of: None
```
Should we pass `spider` here https://github.com/scrapy-plugins/scrapy-crawlera-fetch/blob/06fbebf3135494990468ea56b84cb6eaba26abdf/crawlera_fetch/middleware.py#L106 ?

https://github.com/scrapy/scrapy/blob/master/scrapy/utils/reqser.py#L11

**Comment by starrify** [comment]
Was asked about this same issue as well. Here's a sample spider to reproduce the issue:
```
# coding: utf8

import scrapy


class TestSpider(scrapy.Spider):
    name = 'test'
    custom_settings = {
        'DOWNLOADER_MIDDLEWARES': {
            'crawlera_fetch.CrawleraFetchMiddleware': 585,
        },
        'CRAWLERA_FETCH_ENABLED': True,
        'CRAWLERA_FETCH_APIKEY': 'foo',  # no valid key needed to trigger the issue
    }

    def start_requests(self):
        yield scrapy.Request(
            url='http://httpbin.org/get',
            callback=self.parse,
        )

    def parse(self, response):
        pass
```
Here's the full logs when running the sample spider: https://gist.github.com/starrify/50337688ae7787057e68c91ba733aea9
